# configuration settings and constants

# Fedora image selection
FEDORA_VERSION=36
FEDORA_IMG_REV=1.5

# Name or ID of the existing Azure resource group to utilize.
AZ_RESOURCE_GROUP="Capstone"

# Location to create the image in.
AZ_LOCATION="westus"

# Name of the built image (will have an autogenerated ID appended).
AZ_IMAGE_PREFIX="image-fedora-${FEDORA_VERSION}"

# Size of the disk (in GB).
IMAGE_SIZE=4

# Hyper-V generation of the output image.
AZ_HYPERV_GEN=V2


# constants and derived values
INSTALLER_IMG_URL="https://download.fedoraproject.org/pub/fedora/linux/releases/${FEDORA_VERSION}/Server/x86_64/iso/Fedora-Server-netinst-x86_64-${FEDORA_VERSION}-${FEDORA_IMG_REV}.iso"
INSTALLER_IMG_NAME="${INSTALLER_IMG_URL##*/}"
INSTALLER_IMG_PATH="cache/${INSTALLER_IMG_NAME}"

AZ_INSTALL_VM_PREFIX="temp-installer-vm"

TARGET_BLOCK_DEVICE="/dev/disk/azure/scsi1/lun0"  # should point to the managed data disk
